import { useEffect, useState } from 'react';
import axios from 'axios';
import { Activity, ArrowLeft, Clock3, Database, Gauge, Radio } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:8000';
const duration=s=>`${Math.floor(s/60)}m ${Math.floor(s%60)}s`;
function Metric({icon:Icon,label,value,detail}){return <div className="panel rounded-lg border border-line p-5"><div className="flex justify-between"><span className="font-mono text-[10px] text-mute">{label}</span><Icon className="w-4 h-4 text-trace"/></div><div className="mt-3 font-display text-3xl text-paper">{value}</div><p className="mt-1 text-xs text-mute">{detail}</p></div>}
export default function StatusPage(){const [status,setStatus]=useState(null),[error,setError]=useState(false),[latency,setLatency]=useState([]);const nav=useNavigate(),reduce=useReducedMotion();useEffect(()=>{let active=true;const load=async()=>{try{const {data}=await axios.get(`${API_URL}/status`);if(active){setStatus(data);setLatency(v=>[...v.slice(-19),data.p50_latency_ms||0]);setError(false)}}catch{if(active)setError(true)}};load();const i=setInterval(load,15000);return()=>{active=false;clearInterval(i)}},[]);const max=Math.max(1,...latency);const points=latency.map((v,i)=>`${i*200/Math.max(1,latency.length-1)},${38-v/max*34}`).join(' ');return <main className="min-h-screen bg-ink px-6 py-10 text-paper"><div className="mx-auto max-w-4xl"><button onClick={()=>nav('/')} className="mb-12 flex gap-2 font-mono text-xs text-mute"><ArrowLeft className="w-3.5 h-3.5"/>neuralrag://status</button><p className="font-mono text-xs text-trace"><Radio className="inline w-3 h-3"/> SYSTEM TELEMETRY</p><h1 className="mt-3 font-display text-4xl">Operational status.</h1>{error?<p className="mt-8 text-danger">Status endpoint is unreachable.</p>:<><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Activity} label="UPTIME" value={duration(status?.uptime_seconds||0)} detail="current process"/><Metric icon={Clock3} label="P50 LATENCY" value={`${status?.p50_latency_ms??0}ms`} detail="observed queries"/><Metric icon={Gauge} label="P95 LATENCY" value={`${status?.p95_latency_ms??0}ms`} detail="tail response time"/><Metric icon={Database} label="CACHE HIT RATE" value={`${((status?.cache_hit_rate??0)*100).toFixed(1)}%`} detail="semantic cache"/></div><div className="mt-8 rounded-lg border border-line p-4"><p className="font-mono text-[10px] text-mute">LATENCY TRACE · LAST {latency.length} REFRESHES</p><motion.svg initial={reduce?false:{opacity:0}} animate={{opacity:1}} viewBox="0 0 200 40" className="mt-3 h-12 w-full"><polyline points={points} fill="none" stroke="#4FD8C4" strokeWidth="2"/></motion.svg></div></>}</div></main>}
